---
root: true
extends:
  - '@chookslint/typescript'
parserOptions:
  project: ./tsconfig.json
rules:
  '@typescript-eslint/naming-convention': 'off'
  func-style: 'off'
  multiline-ternary: 'off'
  operator-linebreak: 'off'
