---
extends:
  - '@chookslint/typescript'
parserOptions:
  project: ./tsconfig.json
overrides:
  - files: sample/**/*
    parserOptions:
      project: sample/tsconfig.json
rules:
  '@typescript-eslint/naming-convention': 'off'
  func-style: 'off'
  multiline-ternary: 'off'
  operator-linebreak: 'off'
